# documentation at https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - examples/ILI9341/RotatingCube
          - examples/ILI9341/DrawXBM
          - examples/ILI9341/DrawPaletteImage_4Bit
          - examples/ILI9341/DrawPaletteImage_1Bit
          - examples/ILI9341/Carousel
          - examples/ILI9341/BasicDrawing
          - examples/EPaper/EPaperDemo2_54Pervasive
          - examples/EPaper/EPD_WaveShare_29
    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Install library dependencies
        run: pio lib -g install "https://github.com/PaulStoffregen/XPT2046_Touchscreen/#v1.4" "EspSoftwareSerial @ ^6.15.2"
      - name: Run PlatformIO
        run: pio ci --lib="." --board=d1_mini --board=esp_wroom_02 --board=lolin32
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
